"""Port interfaces for dependency inversion.

Domain layer defines these interfaces (ports).
Infrastructure layer implements them (adapters).
This ensures the domain layer has zero external dependencies.
"""

from __future__ import annotations

from typing import Any, Protocol


class ComfyUIPort(Protocol):
    """Interface for ComfyUI communication."""

    async def get_system_stats(self) -> dict[str, Any]: ...
    async def get_object_info(self, node_class: str | None = None) -> dict[str, Any]: ...
    async def get_queue(self) -> dict[str, Any]: ...
    async def get_history(self, prompt_id: str | None = None) -> dict[str, Any]: ...
    async def queue_prompt(self, workflow: dict[str, Any]) -> dict[str, Any]: ...
    async def interrupt(self) -> None: ...
    async def list_models(self, folder: str) -> list[str]: ...
    async def health_check(self) -> bool: ...
    def get_image_url(self, filename: str, subfolder: str, folder_type: str) -> str: ...


class LLMPort(Protocol):
    """Interface for LLM communication."""

    async def chat(
        self,
        messages: list[dict[str, Any]],
        tools: list[Any] | None = None,
        system: str = "",
    ) -> Any: ...


class SessionPort(Protocol):
    """Interface for session persistence."""

    async def save_messages(self, session_id: str, messages: list[dict[str, Any]]) -> None: ...
    async def load_messages(self, session_id: str) -> list[dict[str, Any]]: ...
    async def list_sessions(self) -> list[dict[str, Any]]: ...
    async def create_session(self, title: str) -> str: ...
    async def delete_session(self, session_id: str) -> None: ...
