"""Port interfaces for dependency inversion.

Domain layer defines these interfaces (ports).
Infrastructure layer implements them (adapters).
This ensures the domain layer has zero external dependencies.
"""

from __future__ import annotations

from typing import Any, Awaitable, Callable, Protocol

from comfyui_agent.domain.models.events import Event, EventType


class ComfyUIPort(Protocol):
    """Interface for ComfyUI communication."""

    async def get_system_stats(self) -> dict[str, Any]: ...
    async def get_object_info(self, node_class: str | None = None) -> dict[str, Any]: ...
    async def get_queue(self) -> dict[str, Any]: ...
    async def get_history(self, prompt_id: str | None = None) -> dict[str, Any]: ...
    async def queue_prompt(self, workflow: dict[str, Any]) -> dict[str, Any]: ...
    async def interrupt(self) -> None: ...
    async def list_models(self, folder: str) -> list[str]: ...
    async def health_check(self) -> bool: ...
    def get_image_url(self, filename: str, subfolder: str, folder_type: str) -> str: ...
    async def upload_image(self, image_data: bytes, filename: str, overwrite: bool = False) -> dict[str, Any]: ...
    async def get_folder_paths(self) -> dict[str, Any]: ...
    async def free_memory(self, unload_models: bool = True, free_memory: bool = True) -> None: ...
    async def close(self) -> None: ...
    async def connect_ws(self) -> None: ...


class LLMPort(Protocol):
    """Interface for LLM communication."""

    async def chat(
        self,
        messages: list[dict[str, Any]],
        tools: list[Any] | None = None,
        system: str = "",
    ) -> Any: ...

    async def close(self) -> None: ...


class SessionPort(Protocol):
    """Interface for session persistence."""

    async def save_messages(self, session_id: str, messages: list[dict[str, Any]]) -> None: ...
    async def load_messages(self, session_id: str) -> list[dict[str, Any]]: ...
    async def list_sessions(self) -> list[dict[str, Any]]: ...
    async def create_session(self, title: str) -> str: ...
    async def delete_session(self, session_id: str) -> None: ...
    async def close(self) -> None: ...
    async def append_message(self, session_id: str, role: str, content: Any) -> int: ...
    async def load_messages_from(self, session_id: str, from_id: int = 0) -> list[dict[str, Any]]: ...
    async def get_session_meta(self, session_id: str) -> dict[str, Any]: ...
    async def update_session_meta(self, session_id: str, **kwargs: Any) -> None: ...
    async def create_child_session(self, parent_id: str, title: str) -> str: ...


EventHandler = Callable[[Event], Awaitable[None] | None]


class EventBusPort(Protocol):
    """Interface for event pub/sub communication."""

    def on(self, event_type: EventType, handler: EventHandler) -> Callable[[], None]: ...
    def on_prefix(self, prefix: str, handler: EventHandler) -> Callable[[], None]: ...
    def on_all(self, handler: EventHandler) -> Callable[[], None]: ...
    async def emit(self, event: Event) -> None: ...
